---
new_page_extension: md
auto_deploy: false
admin_path: ree-boot
webhook_url: 
sections:
- type: heading
  label: Оглавление
- type: document
  path: content/_index.md
  label: Регулярные вырождения
- type: directory
  path: content/post
  label: Записки
  create: all
  match: "**/*"
  templates:
  - post
- type: heading
  label: Котомка
- type: directory
  path: content/authors
  label: Создатели
  create: all
  match: "**/_index.md"
  templates:
  - author
- type: directory
  path: config/_default
  label: Настройки
  create: all
  match: "**/*"
  new_doc_ext: yaml
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.80.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.81.0
